### ISSUE TITLE
Bug: Last tag is `v0.0.7` rather than `0.0.7`

### ISSUE THREAD

**Issue by zoispag** [aquasecurity/trivy-action#11]
Hi @danielpacak,

I tried to use the latest tag, but it failed and i noticed that latest tag includes `v` as part of the tag. Shall I update the README.md or a new tag shall be craeted?

**Comment by danielpacak** [comment]
My bad. I've release with 0.0.7 tag now! Thanks for heads up!

**Comment by zoispag** [comment]
Perfect! Thanks!
