### ISSUE TITLE
New option to define severities when the action should fail

### ISSUE THREAD

**Issue by krisztian-sala** [aquasecurity/trivy-action#119]
Would it be possible to have an additional config option, similar to the `severity`, where we can list the severities that we want to have an error exit code?
For example: I would like to scan for critical, high and medium severity vulnerabilities, but only fail the action if critical or high is found.

**Comment by simar7** [comment]
hi @krisztian-sala - such an option doesn't exist today as you mentioned but this to me feels like a feature that's better done at a Trivy level rather than the Trivy Action.

**Comment by krisztian-sala** [comment]
All right, for now, I used the action twice, first with critical and high, with the exit code 1 and second with medium, exit code 0. Seems to work like this, I'm going to close this issue
