### ISSUE TITLE
The exit-code: '1'  can't stop the workflow 

### ISSUE THREAD

**Issue by guinan34** [aquasecurity/trivy-action#135]
here is my config 
```name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL'
          exit-code: '1'
```
here is the scan result
<img width="995" alt="image" src="https://user-images.githubusercontent.com/16395409/175871717-eb816195-637a-439f-965e-82e4b80fd317.png">

it's indeed scanned out a critical error, but the workflow still succeeded, i don't know why .

**Comment by guinan34** [comment]
@simar7  thanks your help . i just to check the result. still success.   
if i run the command on my local laptop, then `echo $?`, it's indeed returned `1`, but in github action didn't . 
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/16395409/176104701-43906f49-e802-4666-b9a3-08e8641c451b.png">

**Comment by simar7** [comment]
hi @guinan34 - thanks for your patience. It was indeed a bug in Trivy v0.29.1 that has been since patched and released in v0.29.2. I will update Trivy Action to use this version shortly.

**Comment by simar7** [comment]
hi @guinan34 - v0.5.1 is now released with the fix https://github.com/aquasecurity/trivy-action/releases/tag/0.5.1

**Comment by guinan34** [comment]
@simar7  really cool , i tested it. worked now .
