### ISSUE TITLE
trivy sbom for gh dependency-submission

### ISSUE THREAD

**Issue by krol3** [aquasecurity/trivy-action#138]
I'm following the tutorial to create a snapshot to do a [dependency submission](https://docs.github.com/en/rest/dependency-graph/dependency-submission).

I create the snapshot file using trivy: trivy image --output ./outputs/sbom-image-gh.json --format  github krol/go-helloworld. See [here](https://github.com/krol3/helloworld/blob/main/outputs/sbom-image-gh.json)

The json generated is missing this properties: .sha, .ref, .job.id

**Comment by simar7** [comment]
Closing as discussed offline: https://github.com/aquasecurity/trivy-action#using-trivy-to-generate-sbom
