### ISSUE TITLE
Update to 0.30.0

### ISSUE THREAD

**Issue by nyarly** [aquasecurity/trivy-action#146]
We're suffering from https://github.com/aquasecurity/trivy/issues/2375, which appears to be fixed in Trivy 0.30.0, based on timeline of PRs and releases.

Could we please get an update to the action to use 0.30?

**Comment by simar7** [comment]
hi @nyarly - yes there's an open PR for it. We're waiting for Trivy to stabilize https://github.com/aquasecurity/trivy-action/pull/143

thanks for your patience.

**Comment by simar7** [comment]
https://github.com/aquasecurity/trivy-action/releases/tag/0.6.0 is now released with Trivy v0.30.2.
