### ISSUE TITLE
Add a timestamp to scan output in JSON mode

### ISSUE THREAD

**Issue by chipzoller** [aquasecurity/trivy-action#149]
Not sure if this is a trivy-action or just a trivy enhancement. When using the action, if the output mode is JSON, the scan produced does not have a timestamp of the scan. A timestamp is needed when attesting to a scan in order to make policy decisions, such as ensuring the scan was produced before a certain amount of time. Today, this has to be added in a separate step. It would be nice for this to just be added automatically and should be a very simple enhancement.

**Comment by simar7** [comment]
hi @chipzoller - this would be a trivy enhancement. cc @knqyf263

**Comment by chipzoller** [comment]
I believe this is already addressed hence closing.
