### ISSUE TITLE
incorrect API usage for GitHub Dependency Snapshot in entrypoint.sh

### ISSUE THREAD

**Issue by chejn** [aquasecurity/trivy-action#161]
Issue in line 189 - curl command uses -u flag for authentication when authentication should be passed as the following header 
-H "Authorization: token {TOKEN}"

Ref: https://docs.github.com/en/rest/dependency-graph/dependency-submission#create-a-snapshot-of-dependencies-for-a-repository

**Comment by simar7** [comment]
Thanks it seems that it has changed since the initial release. Would you be interested in submitting a PR, @chejn?

**Comment by simar7** [comment]
Fixed with https://github.com/aquasecurity/trivy-action/pull/162
