### ISSUE TITLE
trivy-action for scanning kubernetes cluster

### ISSUE THREAD

**Issue by muddassir-r** [aquasecurity/trivy-action#163]
Is there any GitHub action to scan kubernetes cluster from trivy-action.

**Comment by simar7** [comment]
hi @muddassir-r - what are you trying to accomplish? You could use [Trivy-operator](https://github.com/aquasecurity/trivy-operator) to scan your k8s workloads.

**Comment by muddassir-r** [comment]
@simar7 I was trying to use trivy-action to scan kubernetes cluster, I realize that the scope of trivy-action would be scanning the image build from the docker file which is placed in the repo.
