### ISSUE TITLE
bump trivy to 0.32.1

### ISSUE THREAD

**Issue by SvenOleLuxMD** [aquasecurity/trivy-action#175]
I would like to use the gradle supported Version of trivy in this action.
In v0.32.1 java/gradle support is added --> https://github.com/aquasecurity/trivy/issues/2707
Would be great to use the latest trivy version also in this action.

**Comment by SvenOleLuxMD** [comment]
Haven't read the PRs -> https://github.com/aquasecurity/trivy-action/pull/170 seems to be the PR fpr 0.32.1

**Comment by simar7** [comment]
fixed by https://github.com/aquasecurity/trivy-action/pull/177
