### ISSUE TITLE
 HTTP status: 503 Service Unavailable in Github action pipeline

### ISSUE THREAD

**Issue by amrityamrout** [aquasecurity/trivy-action#180]
Step 1/5 : FROM ghcr.io/aquasecurity/trivy:0.34.0
  received unexpected HTTP status: 503 Service Unavailable
  Warning: Docker build failed with exit code 1, back off 1.279 seconds before retry.
  /usr/bin/docker build -t 290506:2a37db7d2bac4b86970a8f85ca423577 -f "/home/runner/work/_actions/aquasecurity/trivy-action/master/Dockerfile" "/home/runner/work/_actions/aquasecurity/trivy-action/master"
<img width="1114" alt="Screenshot 2022-11-25 at 8 45 27 PM" src="https://user-images.githubusercontent.com/113448556/204014641-ac9b1861-fa95-45a2-826a-65ff34f26c4f.png">

**Comment by simar7** [comment]
this was a intermittent issue on the GHCR side, should be fixed now.
