### ISSUE TITLE
Upgrade trivy-action to use latest trivy release (v0.35.0)

### ISSUE THREAD

**Issue by tusharkshatriya** [aquasecurity/trivy-action#183]
There is a bug in trivy v0.34.0 that has been fixed in the latest version (v0.35.0) https://github.com/aquasecurity/trivy/pull/3102.
Upgrade trivy-action to use the latest version of trivy to fix this.

**Comment by simar7** [comment]
released new trivy action with v0.37.1 trivy https://github.com/aquasecurity/trivy-action/releases/tag/0.9.0
