### ISSUE TITLE
Trivy Action times out since today

### ISSUE THREAD

**Issue by pioneer2k** [aquasecurity/trivy-action#190]
Until ths morning everything worked well. In all our GitHub Actions Workflows the Trivy Image Scanning worked normal and took around 30 seconds.

Since some hours now, the scanning times out. Even increasing the timeout to 15 minutes and disabling the secret scanning does not help. Maybe something is wrong with the trivy database?

Please see our output:

Run aquasecurity/trivy-action@master
Running trivy with options: trivy image  --format sarif --vuln-type  os,library --severity  UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL --output  trivy-results.sarif --ignore-policy  ./trivy_ignore.rego  xxxxxxxxxxxxx.dkr.ecr.eu-central-1.amazonaws.com/cccs/centraladdresssearchservice:qa
Global options:  
2023-01-12T11:03:15.708Z	INFO	Need to update DB
2023-01-12T11:03:15.708Z	INFO	DB Repository: ghcr.io/aquasecurity/trivy-db
2023-01-12T11:03:15.708Z	INFO	Downloading DB...
27.06 MiB / 36.04 MiB [--------------------------------------------->_______________] 75.09% ? p/s ?36.04 MiB / 36.04 MiB [----------------------------------------------------------->] 100.00% ? p/s ?36.04 MiB / 36.04 MiB [----------------------------------------------------------->] 100.00% ? p/s ?36.04 MiB / 36.04 MiB [---------------------------------------------->] 100.00% 14.94 MiB p/s ETA 0s36.04 MiB / 36.04 MiB [---------------------------------------------->] 100.00% 14.94 MiB p/s ETA 0s36.04 MiB / 36.04 MiB [---------------------------------------------->] 100.00% 14.94 MiB p/s ETA 0s36.04 MiB / 36.04 MiB [---------------------------------------------->] 100.00% 13.98 MiB p/s ETA 0s36.04 MiB / 36.04 MiB [---------------------------------------------->] 100.00% 13.98 MiB p/s ETA 0s36.04 MiB / 36.04 MiB [---------------------------------------------->] 100.00% 13.98 MiB p/s ETA 0s36.04 MiB / 36.04 MiB [-------------------------------------------------] 100.00% 22.16 MiB p/s 1.8s2023-01-12T11:03:18.536Z	INFO	Vulnerability scanning is enabled
2023-01-12T11:03:18.536Z	INFO	Secret scanning is enabled
2023-01-12T11:03:18.536Z	INFO	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2023-01-12T11:03:18.536Z	INFO	Please see also https://aquasecurity.github.io/trivy/v0.34/docs/secret/scanning/#recommendation for faster secret detection
2023-01-12T11:08:15.773Z	WARN	Increase --timeout value
2023-01-12T11:08:15.773Z	FATAL	image scan error: scan error: scan failed: failed analysis: analyze error: timeout: context deadline exceeded

**Comment by knqyf263** [comment]
I believe this is not our issue. GitHub Container Registry distributing Trivy DB was slow and it caused timeout in my environment. Others saw timeout with `search.maven.org`. If you are scanning images with JAR/WAR files, it is worth trying `--offline-scan`. You can set it via `trivy.yaml`.
https://aquasecurity.github.io/trivy/v0.36/docs/references/customization/config-file/

**Comment by smartinrub** [comment]
This worked for me, which should be the same as @knqyf263 comment.
```yaml
- name: Run Trivy
  uses: aquasecurity/trivy-action@master
  env:
    TRIVY_OFFLINE_SCAN: true
...
```

**Comment by pioneer2k** [comment]
That is working for me as well

**Comment by erzz** [comment]
gonna add a me-too post to keep track ... seems to really affect java projects only. Node / Go projects seem to be running fast as ever 🤷🏻

**Comment by simar7** [comment]
we've just released a new version of trivy action (https://github.com/aquasecurity/trivy-action/releases/tag/0.9.0) please give it a shot and see if the problem still persists.

**Comment by anshbansal** [comment]
It still fails here for OSS DataHub project https://github.com/datahub-project/datahub/actions/runs/4070080489/jobs/7020725786. Started happening 2 days ago.

**Comment by anshbansal** [comment]
We currently use `aquasecurity/trivy-action@master` in our tags. Is using `aquasecurity/trivy-action@0.9.0` instead recommended?

**Comment by anshbansal** [comment]
This had happened a few weeks ago and we added https://github.com/datahub-project/datahub/pull/7050/files this environment variables based on the github discussions in the issues. But seems that stopped working on 31st-Jan-2023.

**Comment by pioneer2k** [comment]
aquasecurity/trivy-action@master is using v0.9.0 since today and it is using Trivy v0.37.1 - and it has stopped working with this environment variable for us as well. We changed our pipeline to aquasecurity/trivy-action@0.8.0 and it is working again.

**Comment by simar7** [comment]
Thanks for the feedback. We’ll another look at it.

**Comment by b44rawat** [comment]
I am facing same issue with the `@master` tag. and getting below error

```
FATAL	image scan error: scan error: unable to initialize a scanner: 
unable to initialize a docker scanner: failed to parse the image name: could not parse reference:
${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
```

**Comment by knqyf263** [comment]
@b44rawat Your error is something different. The variable is not evaluated well.
