### ISSUE TITLE
ignoring the severity when we use ignore-unfixed: false

### ISSUE THREAD

**Issue by kmganna** [aquasecurity/trivy-action#192]
I am running the trivy vulnerability scan on the docker image in the git action pipeline.

Below is the code.
 `- name: Run Trivy vulnerability scanner on a container uses: aquasecurity/trivy-action@9ab158e8597f3b310480b9a69402b419bc03dbd5  with: image-ref: '${{ inputs.registry }}/${{ inputs.repo_name }}:${{ inputs.image_version }}' format: 'sarif' severity: 'CRITICAL,HIGH,MEDIUM'   output: 'trivy-container-results.sarif' ignore-unfixed: true timeout: ${{ inputs.timeout }}`

The above code is working and giving the results based on the severity of the application and it is ignoring unfixed OS fixes(HIGH, MEDIUM and CRITICAL) and LOW fixes as well. Now if I make ignore-unfixed: false then it is giving all the ignored OS fixes along with "LOW severity".

Requirement is:
If I use ignore-unfixed: false and there is a severity CRITICAL, HIGH, and MEDIUM. The output should be application issues and OS issues in the output file based on severity. It should not be LOW and other issues.

Please suggest how to achieve it.

**For reference:** 

The issue has been discussed in the below section
https://github.com/aquasecurity/trivy/discussions/1687#discussioncomment-4764109

**Comment by knqyf263** [comment]
@AndreyLevchenko I feel like it is a critical issue. Could you help fix it?

**Comment by kmganna** [comment]
@knqyf263 @AndreyLevchenko,  any luck on this issue fix?

**Comment by simar7** [comment]
@AndreyLevchenko worked on a fix which should be in the latest release of the trivy action https://github.com/aquasecurity/trivy-action/releases/tag/0.9.0 , please give it a try. Reopen if issues still persists. Thanks!

**Comment by kmganna** [comment]
@AndreyLevchenko,  thanks, for adding the changes.
The issue has not yet been resolved.

I performed the below tests.

Test 1: 
When we performed:  In the git actions
Ignored-fixed = false

`      - name: Run Trivy vulnerability scanner on a container
        uses aquasecurity/trivy-action@cff3e9a7f62c41dd51975266d0ae235709e39c41 # <====== v0.9.0 - Upgrade Trivy Action version here 
        if: ${{ inputs.scan_container == true }}
        with:
          image-ref: '${{ inputs.registry }}/${{ inputs.repo_name }}:${{ inputs.image_version }}'
          format: 'sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'  # <====== Change "sensitivity" here
          output: 'trivy-container-results.sarif'
          ignore-unfixed: false
          timeout: ${{ inputs.timeout }}
      
      - name: Read the container scanner report ignored false
        shell: bash
        run: |-
          cp  /runner/_work/service/validate-service/trivy-container-results.sarif/runner/_work/service/validate-service/trivy-container-image-results.txt
          cat/runner/_work/service/validate-service/trivy-container-image-results.txt`

output: Published all severity results: LOW, MEDIUM, HIGH, CRITICAL etc...

TEST 2: 
When we performed:  In the git actions
ignore-fixed: true

` - name: Run Trivy vulnerability scanner
        uses aquasecurity/trivy-action@master
        with:
          image-ref: '${{ inputs.registry }}/${{ inputs.repo_name }}:${{ inputs.image_version }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL, HIGH, MEDIUM'
          ignore-unfixed: true

      - name: Read the container scanner report ignored true
        shell: bash
        run: |-
          cp   /runner/_work/service/validate-service/trivy-results.sarif  /runner/_work/service/validate-service/trivy-image-results.txt
          cat /runner/_work/meda-verification-service/meda-verification-service/trivy-image-results.txt`

output: Published the CRITICAL, HIGH, and MEDIUM reports but it has not captured the attached results for the ECR image. AWS captured these results.
![Screenshot 2023-02-07 at 1 22 13 pm](https://user-images.githubusercontent.com/118502668/217133159-b9a6d0b0-a415-447c-8d8c-b3f9bdf63219.png)

Please do let me know if you need more information, thank you in advance.

Regards,
Krishna Mohan

**Comment by kmganna** [comment]
@simar7 @AndreyLevchenko Could you please provide an update?

**Comment by simar7** [comment]
I've pinged @AndreyLevchenko to see if he can take another look at it.

**Comment by AndreyLevchenko** [comment]
@kmganna 
The changes introduce new parameter `limit-severities-for-sarif` to override default sarif behavior. So it should be set to `false` in order to use `severities` parameter
