### ISSUE TITLE
Rename security-checks to scanners

### ISSUE THREAD

**Issue by sadovnikov** [aquasecurity/trivy-action#210]
In Trivy v0.37.0 the `--security-checks` arguments is renamed to `--scanners` https://github.com/aquasecurity/trivy/releases/tag/v0.37.0

Trivy Action 0.9.1 gives
```
WARN	'--security-checks' is deprecated. Use '--scanners' instead.
```

**Comment by chrisdleech-pol** [comment]
https://github.com/aquasecurity/trivy-action/pull/201

I was about to raise a PR for this, but this PR is already outstanding to fix. It needs a review. It also failed a build, so I suspect needs a little work.

Would be good to get this in place to remove this warning.
