### ISSUE TITLE
Uploading sarif files: instance.runs[0].tool.driver.rules contains duplicate item

### ISSUE THREAD

**Issue by lucmichalski** [aquasecurity/trivy-action#22]
Hi guys,

Hope you are all well !

I tried trivy action and I have the following error:
```sh
Uploading sarif files: ["trivy-results.sarif"]
Error details: instance.runs[0].tool.driver.rules contains duplicate item
```

<img width="986" alt="Screenshot 2020-12-14 at 15 33 21" src="https://user-images.githubusercontent.com/1963546/102093802-deef4e00-3e21-11eb-9484-8edb348b17ad.png">

Is there a parameter to set in trivy to avoid duplicates ?

Here is my workflow file:
https://github.com/lucmichalski/prestashop-docker/blob/trivy/.github/workflows/security.yml

Cheers,
Luc Michalski

**Comment by simar7** [comment]
hi @lucmichalski - I'd like to repro this, is the image you were running this against public? Also would it be possible for you to share the generated SARIF output? 

You can do so by running trivy as:
```
trivy image --format=template --template="@contrib/sarif.tpl" <imageName>
```

You can find a copy of `sarif.tpl` here: https://github.com/aquasecurity/trivy/blob/master/contrib/sarif.tpl

**Comment by beevelop** [comment]
Experiencing the same issue with an image scan for Docker-Android:
```
Run github/codeql-action/upload-sarif@v1
  with:
    sarif_file: trivy-results.sarif
    checkout_path: /home/runner/work/docker-android/docker-android
    token: ***
    matrix: null
  env:
    platforms: linux/amd64
    imageName: ***/android
Uploading sarif files: ["trivy-results.sarif"]
Error details: instance.runs[0].tool.driver.rules contains duplicate item
Error: Unable to upload "trivy-results.sarif" as it is not valid SARIF:
- instance.runs[0].tool.driver.rules contains duplicate item
Error: Unable to upload "trivy-results.sarif" as it is not valid SARIF:
- instance.runs[0].tool.driver.rules contains duplicate item
    at validateSarifFileSchema (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:142:15)
    at uploadFiles (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:201:9)
    at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:91:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async run (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:34:29)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:46:9)
```

Build: https://github.com/beevelop/docker-android/pull/29/checks?check_run_id=1891411385

**Comment by simar7** [comment]
@rahul2393 - can you take a look into this?

**Comment by rahul2393** [comment]
The issue is happening because of duplicate ruleID, I am creating patch to append Package Name too in ID

**Comment by rahul2393** [comment]
@simar7 help review PR

**Comment by simar7** [comment]
@lucmichalski https://github.com/aquasecurity/trivy/pull/913 was merged and the next release of Trivy/TrivyAction will support it.

**Comment by beevelop** [comment]
Thank you both 🙏

**Comment by jsjoeio** [comment]
Is this fix in the latest release of TrivyAction?

**Comment by simar7** [comment]
> Is this fix in the latest release of TrivyAction?

Trivy Action uses the latest released version of Trivy https://github.com/aquasecurity/trivy-action/blob/master/Dockerfile#L1 

Trivy recently had a new release which includes this fix so by the virtue of that the new Trivy Action will also have it.

**Comment by jsjoeio** [comment]
Thanks for the quick response! That's what I thought but for some reason, I'm still seeing this error:

https://github.com/cdr/code-server/pull/3296/checks?check_run_id=2512446010#step:5:158

Any ideas on what we might be doing wrong?

**Comment by simar7** [comment]
@rahul2393 could you look into this?

**Comment by simar7** [comment]
> Thanks for the quick response! That's what I thought but for some reason, I'm still seeing this error:
> 
> 
> 
> https://github.com/cdr/code-server/pull/3296/checks?check_run_id=2512446010#step:5:158
> 
> 
> 
> Any ideas on what we might be doing wrong?
> 
> 
> 
> Additional context: our `ci.yaml` pointing at the [trivy jobs](https://github.com/cdr/code-server/blob/jsjoeio/fix-trivy/.github/workflows/ci.yaml#L410-L466)

Thanks. We'll investigate and get back to you.

**Comment by rahul2393** [comment]
@simar7 please help check this https://github.com/aquasecurity/trivy/pull/984

**Comment by douglasduteil** [comment]
I'm experiencing the same 🐛 on some image
Thanks for the PR @rahul2393

**Comment by rahul2393** [comment]
@jsjoeio Update your workflow to use latest commit in master branch I see you are using previous commitID here
https://github.com/cdr/code-server/blob/main/.github/workflows/ci.yaml#L450, the issue should be fixed.

**Comment by jsjoeio** [comment]
Awesome, we'll go ahead and update that. Thanks for getting a fix out so quickly! We really appreciate it.

**Comment by jsjoeio** [comment]
@rahul2393 oh no, I'm seeing the same error. [See logs](https://github.com/cdr/code-server/pull/3368/checks?check_run_id=2568798059).

![image](https://user-images.githubusercontent.com/3806031/118018813-20baec80-b30d-11eb-8f97-7fbebeb5d83f.png)

I updated it to use the latest commit in the master branch [here](https://github.com/cdr/code-server/pull/3368/files#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddR474).

Am I missing something else?

**Comment by rahul2393** [comment]
Checking

**Comment by rahul2393** [comment]
@jsjoeio I just ran the latest fix here in my forked version of your repo https://github.com/rahul2393/code-server/runs/2573437202?check_suite_focus=true, it passed, so we will not do a new release and you can then use it

**Comment by jsjoeio** [comment]
Thanks for taking a closer look! 

> it passed, so we will not do a new release and you can then use it

Sorry, this confused me a bit. Are you saying the current version works and I should try again or are you saying you are going to push a new release and then I can use that?

**Comment by rahul2393** [comment]
Sorry I did typo in previous message, we are going to push a new version then you can use it, I will inform you.

**Comment by rahul2393** [comment]
@jsjoeio can you check this one now? 
https://github.com/aquasecurity/trivy-action/releases/tag/0.0.17

**Comment by jsjoeio** [comment]
@rahul2393 that worked!! Thanks so much 🙌 

https://github.com/cdr/code-server/pull/3368/checks?check_run_id=2578181406

**Comment by knqyf263** [comment]
@jsjoeio Thanks for your confirmation! We're sorry for the inconvenience 🙏

**Comment by simar7** [comment]
@lucmichalski please feel free to reopen this if your issue still persists.
