### ISSUE TITLE
Allow scanning of image tarballs

### ISSUE THREAD

**Issue by AntonOellerer** [aquasecurity/trivy-action#23]
Hey,
Thank you for this nice action!
Would it be possible to support scanning image tarballs as generated by e.g. [jib](https://github.com/GoogleContainerTools/jib/) (Like it can already be done by trivy by using the `--input` flag)
Best regards
Anton

**Comment by simar7** [comment]
hi @AntonOellerer - at the moment we don't have any plans to add that as a feature. What's your use case? As always we'll be happy to take a look at your contribution for it if you had one in mind.

**Comment by AntonOellerer** [comment]
Hey,
the advantage for us would be that we would not have to push the image to a remote repository each time or hassle with setting up a local one.
I for now solved it by using the docker image directly, but maybe I will get around to submit a PR.
Best regards
Anton

**Comment by hakusaro** [comment]
@simar7 I'm actually in the same boat -- I'd like to be able to run against kaniko containers that have been built elsewhere, but trivy needs to take them in image tar format.

**Comment by simar7** [comment]
thanks folks for your feedback - we will take a look into this again.

**Comment by simar7** [comment]
@rahul2393 - could you look into this

**Comment by simar7** [comment]
Any update on this @rahul2393?

**Comment by rahul2393** [comment]
@simar7 yes please review https://github.com/aquasecurity/trivy-action/pull/34

**Comment by simar7** [comment]
hi @hakusaro and @AntonOellerer - we just released https://github.com/aquasecurity/trivy-action/releases/tag/0.0.13 which includes the `--input` functionality. Please give it a shot. Feel free to reopen this issue if something isn't right. Thanks.

**Comment by hakusaro** [comment]
@simar7 thank you so much! I really appreciate it!
