### ISSUE TITLE
Bump Trivy version to >= 0.44

### ISSUE THREAD

**Issue by bodgit** [aquasecurity/trivy-action#250]
I'd like to migrate from the tfsec action to this trivy-based one, however I need at least version 0.44 for it to be usable. As the action hardcodes the version of Trivy it needs to be bumped rather than me add something like the following to my workflows:
```yaml
with:
  version: 0.44.0
```
Hence this request :wink:

I can see there's been some work to create a workflow for automatically doing this, but I can create a PR if needed based on the last version bump.

**Comment by simar7** [comment]
Fixed with https://github.com/aquasecurity/trivy-action/pull/256
