### ISSUE TITLE
How to get the exit code of the trivy-action?

### ISSUE THREAD

**Issue by sumanth-lingappa** [aquasecurity/trivy-action#330]
My workflow file is [HERE](https://github.com/netscaler/ansible-collection-netscaleradc/blob/c412329929d2326ea91f80ea05944b6b7ec7d931/.github/workflows/trivy.yml#L16)

**I would like to fail the workflow** if the **trivy-action** found vulnerabilities. I have done this in my [bandit workflow](https://github.com/netscaler/ansible-collection-netscaleradc/blob/8f73b9a6fb945e727931ff59adbf9c4616018c6a/.github/workflows/bandit.yml#L43) in the same repo

Since I am **using** the trivy-action, I am unable to get the exit-code of the trivy-action run.

Can anyone please help?

**Comment by nikpivkin** [comment]
Hi @sumanth-lingappa !

The README contains examples of how to use the action and a description of the [arguments](https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#inputs). To terminate a workflow with an error, pass the `exit-code: '1'` argument. Don't forget to specify the ` if: always()` condition if you want to load the results to the security page regardless of the status of the workflow.

**Comment by sumanth-lingappa** [comment]
Thank you @nikpivkin for your reply, 

In which step should I pass `if: always()`?

**Comment by nikpivkin** [comment]
@sumanth-lingappa At the upload step of the report, for example, when using `upload-sarif`.

**Comment by sumanth-lingappa** [comment]
@nikpivkin, I have updated my trivy workflow as you mentioned. However, the trivy scan is failing, but there is no such activity in security tab.
Please help.
Workflow file: [HERE](https://github.com/netscaler/ansible-collection-netscaleradc/blob/91d443d500b55295c6ff5d80e09c278f6d2c5c14/.github/workflows/trivy.yml)
Reference Pull request: https://github.com/netscaler/ansible-collection-netscaleradc/pull/411

![image](https://github.com/aquasecurity/trivy-action/assets/42572246/c89b9415-2126-42cf-8034-efe418a130ef)

Trivy workflow details: https://github.com/netscaler/ansible-collection-netscaleradc/actions/runs/8684242656/job/23811506482?pr=411

![image](https://github.com/aquasecurity/trivy-action/assets/42572246/2c0cfc3f-cdc9-4b19-848b-e7a269dcc64f)

![image](https://github.com/aquasecurity/trivy-action/assets/42572246/68f7cf36-e471-4199-aef7-e0caaf25315a)

![image](https://github.com/aquasecurity/trivy-action/assets/42572246/f22a0059-b636-4f8e-a1a7-8cbaa015b865)

**Comment by sumanth-lingappa** [comment]
Thank you @nikpivkin, I get the results now.
![image](https://github.com/aquasecurity/trivy-action/assets/42572246/a87d26ea-0b6d-4558-999e-819d656d876a)


I used to get a GitHub comment before (Ref: [PR#390](https://github.com/netscaler/ansible-collection-netscaleradc/pull/390). But I dont get this anymore? Can you please help how can I get a comment from github-advanced-security via TRIVY as below?

![image](https://github.com/aquasecurity/trivy-action/assets/42572246/567b5d3a-8142-46af-ba5e-23208813c790)

**Comment by nikpivkin** [comment]
Unfortunately I can't help with this and I don't think it's related to Trivy. Try to find it in the documentation.

**Comment by sumanth-lingappa** [comment]
Sure @nikpivkin, I will close this one then. Thanks a lot for your help.
