### ISSUE TITLE
Support or Document how to scan image in remote private repository

### ISSUE THREAD

**Issue by erzz** [aquasecurity/trivy-action#36]
Documentation (or the lack of) suggests that the action doesn't support pulling of remote image to scan, particularly private registries.

There are no inputs for credentials but perhaps a `docker login` step would work? 🤷🏻 

Either way we would like this supported in the action, just like the standard binary supports, because we often would like to run this as a seperate job from the build job and/or scan multiple images/tags

**Comment by simar7** [comment]
Thanks @erzz we'll take a look.

@rahul2393 could you investigate this

**Comment by rahul2393** [comment]
Thanks @erzz for reporting the issue, updated the Readme to have steps to pull private registries here https://github.com/aquasecurity/trivy-action/pull/42, please let us know if you find any issues.

**Comment by erzz** [comment]
@rahul2393 - Looking good! Great work!

I guess there are other variations that could be used for GCR too such as

```
TRIVY_USERNAME: _json_key
TRIVY_PASSWORD: /path/to/credential.json
```

or using the `google-github-actions/setup-gcloud@master` action with `export_default_credentials: true` in a preceding step I guess - but the current doc is good and self-contained examples

Thanks!
