### ISSUE TITLE
Question: build image if doing filesystem scan?

### ISSUE THREAD

**Issue by jsjoeio** [aquasecurity/trivy-action#37]
Hi there!

I am new to Trivy and have a basic question.

Is it necessary to build the Docker image if we're just doing a filesystem scan?

Thanks!

**Comment by simar7** [comment]
Hi @jsjoeio - no it is not as you can use the filesystem scan feature directly.

**Comment by jsjoeio** [comment]
Cool! Thank you!

**Comment by simar7** [comment]
We improved the readme a little in order for this ambiguity to go away as well https://github.com/aquasecurity/trivy-action/pull/43

**Comment by jsjoeio** [comment]
Oh fantastic! I'm sure that will help others when they're first getting started with `trivy-action`
