### ISSUE TITLE
Upgrade GitHub Actions versions in workflow.yml and README.md

### ISSUE THREAD

**Issue by obounaim** [aquasecurity/trivy-action#373]
Description:
Currently the [workflow.yml](https://github.com/aquasecurity/trivy-action/blob/master/workflow.yml) and [README.md](https://github.com/aquasecurity/trivy-action/blob/master/README.md) are using deprecated Github Actions versions.

The following GitHub Actions should be upgraded to their latest versions:
- actions/checkout from v2 to v4
- github/codeql-action/upload-sarif from v2 to v3
   
More info here:
https://github.com/github/codeql-action#supported-versions-of-the-codeql-action
https://github.com/actions/checkout

I can work on this issue and submit a PR.

**Comment by simar7** [comment]
Thanks for the report, we'll definitely appreciate a PR if you decide to submit.
