### ISSUE TITLE
Fix Trivy version

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy-action#39]
The latest Trivy might break compatibility. The version should be fixed.
https://github.com/aquasecurity/trivy-action/blob/master/Dockerfile#L1

**Comment by simar7** [comment]
> The latest Trivy might break compatibility. The version should be fixed.
> https://github.com/aquasecurity/trivy-action/blob/master/Dockerfile#L1

Oh I see. `--skip-dirs` is the one change that comes to my mind, are there others you can think of? In any case we should pin it as you said.

**Comment by simar7** [comment]
Filed an issue https://github.com/aquasecurity/trivy-action/issues/40

**Comment by knqyf263** [comment]
v0.17.0 had some bugs and it affected fs scanning.
https://github.com/aquasecurity/trivy/issues/983
https://github.com/aquasecurity/trivy/issues/968

**Comment by simar7** [comment]
Thanks for the heads up! We have pinned it going forwards https://github.com/aquasecurity/trivy-action/pull/41
