### ISSUE TITLE
Update trivy action to use the latest version of Trivy

### ISSUE THREAD

**Issue by psjamesh** [aquasecurity/trivy-action#400]
We're getting rate-limited by GitHub trying to pull the Trivy DB which is resolved in Trivy release 0.56.0, see this pull request:

https://github.com/aquasecurity/trivy/pull/7592

When will the Trivy action be updated to use this version of Trivy?

**Comment by DChevrier1** [comment]
I second this (upgrading to 0.56.1) as we are getting those errors in our pipelines as well.  Thank you

**Comment by mengland-noaa** [comment]
This is affecting our pipelines as well.

**Comment by mbeauregard3** [comment]
This is affecting our pipelines as well.

**Comment by simar7** [comment]
See https://github.com/aquasecurity/trivy-action/pull/387
