### ISSUE TITLE
trivy-checks policy too many requests error and ECR repo is empty

### ISSUE THREAD

**Issue by billhammond-dev** [aquasecurity/trivy-action#431]
```ERROR	[misconfig] Falling back to embedded checks	err="failed to download built-in policies: download error: OCI repository error: 1 error occurred:\n\t* GET https://ghcr.io/v2/aquasecurity/trivy-checks/manifests/1: TOOMANYREQUESTS: retry-after: 124.424µs, allowed: 44000/minute\n\n"```

This is a similar issue to https://github.com/aquasecurity/trivy-action/issues/389 #389 

Hey folks, there seems to be an ECR repo for the checks policy but it is empty:
https://gallery.ecr.aws/aquasecurity/trivy-checks

I was able to redirect to this using the env in the action like so:
      env:
        TRIVY_CHECKS_BUNDLE_REPOSITORY: public.ecr.aws/aquasecurity/trivy-checks

But obviously nothing is there to download.

Right now this is killing any pipelines requiring the policies to be downloaded

**Comment by billhammond-dev** [comment]
forcing a version seems to work here:
version: "v0.57.0"
in the with: section.

I

**Comment by RainbowMango** [comment]
See #389

**Comment by billhammond-dev** [comment]
fix in more recent versions of trivy cli - which can be set in this action's arguments if needed. I'm sure shortly there will be another action release that includes a newer trivy cli as the default as well
