### ISSUE TITLE
Feature-request: Filter vulnerabilities through OPA rego language

### ISSUE THREAD

**Issue by anandg112** [aquasecurity/trivy-action#49]
I would like to use the `--ignore-policy` flag to filter vulnerabilities with OPA rego language
https://aquasecurity.github.io/trivy/v0.18.1/examples/filter/#by-open-policy-agent

I have a PR for this as well - https://github.com/aquasecurity/trivy-action/pull/48

**Comment by simar7** [comment]
thanks I've merged your PR, it will be available in the next release
