### ISSUE TITLE
Bug: cache-dir input is causing an error

### ISSUE THREAD

**Issue by vlaurin** [aquasecurity/trivy-action#50]
I've been trying to use the `cache-dir` input introduced in commit b38389f8efef9798810fe0c5b5096ac198cffd54 and consistently get the following error when that input is set:

```
Running trivy with options:  --no-progress  --format  table --exit-code  1 --ignore-unfixed --vuln-type  os,library --severity  CRITICAL,HIGH --cache-dir  /tmp/trivy  ghcr.io/xxx/xxx:xxx
Incorrect Usage: flag provided but not defined: -cache-dir

NAME:
   trivy image - scan an image

USAGE:
   trivy image [command options] image_name

OPTIONS:
... omitted for brevity
```

This seems to affect all recent versions of this action from v0.0.14 to and including v0.0.17.

I've had a quick look and this error seems to make sense: as per [Trivy usage](https://aquasecurity.github.io/trivy/v0.18.3/usage/) `--cache-dir` is a global option which must be passed before the command. However the present implementation of this action passes it as a command option instead: 

https://github.com/aquasecurity/trivy-action/blob/master/entrypoint.sh#L89-L97

**Comment by simar7** [comment]
thanks for the issue @vlaurin.

@rahul2393 - could you look into it?

**Comment by simar7** [comment]
Ah looks like you already have a PR in progress @vlaurin - thanks we'll take a look at that

**Comment by rahul2393** [comment]
Looks like I only have to review the PR. looks good to me
