### ISSUE TITLE
Aqua Trivy for Openshift private registry

### ISSUE THREAD

**Issue by sookeke** [aquasecurity/trivy-action#64]
I'm working with Openshift Container and I want to know how to use Aqua trivy to scan image in our container registry

**Comment by krol3** [comment]
Hi @sookeke , are you trying to use in the CI/CD ? You can build the image and use trivy to validate the vulnerabilities. Check this sample: https://github.com/aquasecurity/trivy-action#workflow

**Comment by sookeke** [comment]
@krol3  Thank you, I figured this out
