### ISSUE TITLE
How to run trivy action with local image

### ISSUE THREAD

**Issue by pratik-parikh01** [aquasecurity/trivy-action#68]
In my build workflow, i first build the image, push to private registry and then run trivy action. This takes time since trivy has to fetch the image from the private registry. Is there a way this could work with local image? This will save time for larger images.

**Comment by simar7** [comment]
You could use the fs scan option?

**Comment by pratik-parikh01** [comment]
> You could use the fs scan option?

I want to scan the entire image like how we scan it but don't want to "pull" the image from some private repository because i already have it locally

**Comment by pratik-parikh01** [comment]
> You could use the fs scan option?

fs scan just scans the filesystem but i need the entire image to be scanned

**Comment by ShubhamPalriwala** [comment]
Even I am looking for a solution for this as we do not push all our local builds to a CR! any way to do this?

**Comment by mygzi** [comment]
You can provide a local image tag via `image-ref`, no need to push to a registry first.

**Comment by pratik-parikh01** [comment]
My bad, this works with local images too without pushing to registry. It's just that I was using podman store for storing images instead of docker store. Another unrelated issue is that trivy was not being able to check podman image store because of some socket issue. Example logs:
```
2023-08-14T08:38:03.303Z	FATAL	image scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:
	* unable to inspect the image (<imagename>): Error response from daemon: No such image: <imagename>
	* containerd socket not found: /run/containerd/containerd.sock
	* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
	* GET <imagename>: UNAUTHORIZED: access to the requested resource is not authorized; map[]
```
The "error" number 3 (`unable to initialize Podman client`) was the issue
In any case, you guys can close this issue, everything is resolved from my end. Thanks
