### ISSUE TITLE
--skip-dirs broken in 0.0.21 latest release

### ISSUE THREAD

**Issue by vishiy** [aquasecurity/trivy-action#72]
We started seeing this issue because our github actions have started failing as --skip-dirs are being scanned and thats failing those actions.

**Comment by simar7** [comment]
This should be fixed in the latest release. Could you give it another shot with v0.1.0? Let us know if you still need help.

**Comment by simar7** [comment]
Let us know if you still have a problem by reopening this issues. Thanks.
