### ISSUE TITLE
GitHub Code Scanning shows all vulnerabilities 

### ISSUE THREAD

**Issue by lucacome** [aquasecurity/trivy-action#77]
After this https://github.com/aquasecurity/trivy-action/pull/73 all the vulnerabilities show up in the Code scanning alerts. 

I see from the PR that this is a feature, but now all the images are flagged as vulnerable even though there isn't a fix available (OS packages). 

Should this feature take into consideration the `ignore-unfixed` flag? 
Or how is this supposed to work? Because at the moment we have 400+ alerts that we can't fix in any way since those packages are in the base image and don't have a fix.

Thanks!

**Comment by simar7** [comment]
Thank you for your feedback @lucacome - I do agree with you that it should take the ignore-unfixed flag into consideration (and potentially others as well). It would require some additional logic to handle the existing options. 

@rahul2393 would you be able to take a look at this?

**Comment by simar7** [comment]
@lucacome - I've just merged the PR that should address this, thanks @rahul2393. Could you try to pin with a version of: `2a2157e` to use the feature to try it out? If all looks good, we'll cut a release soon! thank you.

**Comment by lucacome** [comment]
Seems to be working fine @simar7 🎉
