### ISSUE TITLE
releases with major versions / semantic versioning

### ISSUE THREAD

**Issue by rethab** [aquasecurity/trivy-action#81]
hey @simar7 ,

it looks like there are no major versions published and the recommended practice is to include this action from the `master` branch. That's a bit too yolo for me 😄 

Are there any plans on publishing a version that can be referenced without going all the way to the patch-level? Ideally, I can reference a version that gives me all fixes and features, but no breaking changes.

If that's something you'd like help with, please let me know and I'll be happy to help.

**Comment by simar7** [comment]
> hey @simar7 ,
> 
> 
> 
> it looks like there are no major versions published and the recommended practice is to include this action from the `master` branch. That's a bit too yolo for me 😄 
> 
Where did you see this?
> 
> 
> Are there any plans on publishing a version that can be referenced without going all the way to the patch-level? Ideally, I can reference a version that gives me all fixes and features, but no breaking changes.
> 
We should do proper semantic versioning. I'll add that to our list. But that still shouldn't prevent you from using a released version. 
> 
> 
> If that's something you'd like help with, please let me know and I'll be happy to help.

**Comment by simar7** [comment]
https://github.com/aquasecurity/trivy-action/releases/tag/0.1.0 is now available. Let us know if you still need help.

**Comment by rethab** [comment]
Hi @simar7,

Thanks for your response.

The `master` is referenced in the README. I suspect most people are just going to copy whatever is in the README :)

I should have been more clean with what I meant regarding semantic versioning, sorry. What I meant was that it would be nice to be able to reference e.g. `v1` in my workflow rather than a specific version such as `v0.0.22`. The former would allow me to profit from patches whenever they become available without having to change my workflow. At the same time, I am guarded from breaking changes as they would be released in a major version. Dependabot could help with keeping the major versions up to date: [Keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot).

However it looks like this would currently be a manual process. You'd have to create a separate tag `v1` that points to the latest patch version (e.g. `v1.0.1`). Whenever there's a new patch or minor update, the `v1` tag needs to be moved. To the best of my knowledge, GitHub Actions doesn't support resolving major versions automatically so this would be some manual work. For example, the `actions/checkout` from GitHub also seems to be manually moving their major tag along (at least that's what I suspect [based on the tag message](https://github.com/actions/checkout/releases/tag/v2) and it was created one day after the patch version was created).

Anyways, I'm probably asking a bit too much here so never mind.

Thanks for this great action!

**Comment by rethab** [comment]
Sorry, one more comment if I may :)

Your release `0.1.0` seems to be missing the `v` prefix. This means your action would need to be referenced like so:
```yaml
uses: aquasecurity/trivy-action@0.1.0
```

whereas it is custom to reference actions with the `v` prefix, e.g.
```yaml
uses: actions/checkout@v1.0.0
```

Here's an example from `actions/checkout` (note the v prefix in the middle):
![image](https://user-images.githubusercontent.com/2222044/141766947-166fcd03-b34e-4172-b354-de7e57228f76.png)

And this is what yours looks like:
![image](https://user-images.githubusercontent.com/2222044/141766987-9bd64bff-e345-4dc4-ad6c-9abd488b8fba.png)

**Comment by rethab** [comment]
Hi @simar7 what do you think about my proposal? I think it would be very nice for users to be able to stay up to date without referencing `master` or having to check back here if there's a new version.
