### ISSUE TITLE
Feature: Add support for --ignore-unfixed

### ISSUE THREAD

**Issue by zoispag** [aquasecurity/trivy-action#9]
Would it be possible to add support for `--ignore-unfixed` flag in the action?

I tried many things but I haven't figured it out the proper syntax yet to open a Pull Request.

So far I've tried:

- `- '${{ inputs.ignore-unfixed == true && echo --ignore-unfixed }}'`
- `- '${{ inputs.ignore-unfixed }} == true && echo "--ignore-unfixed"'`
- `- '${{ inputs.ignore-unfixed }} == "true" && echo "--ignore-unfixed"'` & 
- `- '${{ inputs.ignore-unfixed == "true" && echo "--ignore-unfixed" }}'`

Not sure how these `${{ }}` are expanded. Any help is appreciated.

**Comment by danielpacak** [comment]
Hi @zoispag Got your point. What about taking the advantage of the fact that running trivy as

```
trivy image alpine:3
```

is equivalent of

```
trivy image --ignore-unfixed=false alpine:3
```

Having said that, I believe you could define a new optional input param and set its default value to `false`, and the finally add it to the action's command:

```
trivy image --ignore-unfixed=${{ inputs.ignore-unfixed }} alpine:3
```
WDYT?

**Comment by zoispag** [comment]
I will give it a try right away and I will let you know. Thanks for the immediate response @danielpacak .

**Comment by zoispag** [comment]
It works. I will open a PR right away :)
